import { createAsyncActionSet } from '../lib/action-helper';

export default {
  GET_PENDING_PAYMENTS_CAR_LIST: createAsyncActionSet('GET_PENDING_PAYMENTS_CAR_LIST'),
  SET_PENDING_PAYMENTS_CAR_LIST_PAGING: 'SET_PENDING_PAYMENTS_CAR_LIST_PAGING',
  RESET_PENDING_PAYMENTS_CAR_LIST_PAGING: 'RESET_PENDING_PAYMENTS_CAR_LIST_PAGING',
  DELETE_PENDING_PAYMENTS_CAR_LIST: 'DELETE_PENDING_PAYMENTS_CAR_LIST',
  RESET_PENDING_PAYMENTS_CAR_LIST: 'RESET_PENDING_PAYMENTS_CAR_LIST',
};
